name: project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.0
  equatable: ^2.0.5
  firebase_core: ^2.9.0
  firebase_database: ^10.1.0
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_gif: ^0.0.4
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  intl: ^0.18.0
  logger: ^1.3.0
  rive: 0.9.1
  sleek_circular_slider: ^2.0.1
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/
