// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdQyxffZnXUtAC-bBOOE7fuwC6RZqVOL4',
    appId: '1:430741015221:web:96d24e14798ecb01e14cfc',
    messagingSenderId: '430741015221',
    projectId: 'weatherme-fcc6a',
    authDomain: 'weatherme-fcc6a.firebaseapp.com',
    databaseURL: 'https://weatherme-fcc6a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weatherme-fcc6a.appspot.com',
    measurementId: 'G-TD655ZBTX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9oLNAdQFPp2kCTaCz1d8shnO-dZ9KFtI',
    appId: '1:430741015221:android:40e7ef868c0e1de7e14cfc',
    messagingSenderId: '430741015221',
    projectId: 'weatherme-fcc6a',
    databaseURL: 'https://weatherme-fcc6a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weatherme-fcc6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZQa69XvQihw-wSH_Ls2a6Ul3WROWqi7Y',
    appId: '1:430741015221:ios:de893860a47a4952e14cfc',
    messagingSenderId: '430741015221',
    projectId: 'weatherme-fcc6a',
    databaseURL: 'https://weatherme-fcc6a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weatherme-fcc6a.appspot.com',
    iosClientId: '430741015221-uavfvrlj10o10llsqm2qdg2v4pe7odqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZQa69XvQihw-wSH_Ls2a6Ul3WROWqi7Y',
    appId: '1:430741015221:ios:de893860a47a4952e14cfc',
    messagingSenderId: '430741015221',
    projectId: 'weatherme-fcc6a',
    databaseURL: 'https://weatherme-fcc6a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weatherme-fcc6a.appspot.com',
    iosClientId: '430741015221-uavfvrlj10o10llsqm2qdg2v4pe7odqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
